[env:esp32wroom]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 460800
board_build.partitions = partitions_ota.csv

lib_deps =
    h2zero/NimBLE-Arduino@^1.4.1
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^7.3.0
    links2004/WebSockets@^2.4.1

lib_ldf_mode = deep

build_flags =
    -D CONFIG_BT_NIMBLE_ROLE_CENTRAL=1
    -D CONFIG_BT_NIMBLE_ROLE_PERIPHERAL=0
    -D CONFIG_BT_NIMBLE_ROLE_OBSERVER=1
    -D CONFIG_BT_NIMBLE_ROLE_BROADCASTER=0
    -D CONFIG_BT_NIMBLE_MAX_CONNECTIONS=1
    -D WB_VERSION='"v2.4.3-wroom"'

    ; No ARDUINO_USB_CDC_ON_BOOT on WROOM (native UART0)

; OTA : pio run -e ota -t upload --upload-port <IP>
[env:ota]
extends = env:esp32wroom
upload_protocol = espota
upload_port = wallbox-gw.local